# Comparação das expectativas de vida nos distritos do município de São Paulo

In [1]:
import pandas as pd

In [4]:
bruto_df = pd.read_csv('dados/brutos/obitos-resid_por_idade_distrito-resid_2010-2019.csv', sep=';', skiprows=3, skipfooter=6, encoding='latin-1', engine='python')

In [9]:
bruto_df

,Idade Detalhada,Água Rasa,Alto de Pinheiros,Anhanguera,Aricanduva,Artur Alvim,Barra Funda,Bela Vista,Belém,Bom Retiro,...,Vila Jacuí,Vila Leopoldina,Vila Maria,Vila Mariana,Vila Matilde,Vila Medeiros,Vila Prudente,Vila Sônia,Ignorado,Total
0,< 1 hora,5,-,6,4,10,-,1,4,3,...,9,2,17,-,6,6,11,5,5,740
1,1 hora,2,-,7,4,13,1,2,3,2,...,15,-,11,8,8,12,8,8,6,910
2,2 horas,1,1,3,1,1,-,3,1,1,...,5,-,6,1,-,7,2,2,-,252
3,3 horas,3,-,2,2,2,2,-,2,1,...,4,-,5,1,-,1,5,2,-,165
4,4 horas,1,-,4,-,3,1,-,2,1,...,3,-,3,-,1,-,1,-,-,155
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
180,115 anos,-,-,-,-,-,-,-,-,-,...,-,-,-,-,-,-,-,-,-,1
181,116 anos,-,-,-,-,-,-,-,-,-,...,-,-,-,-,-,-,-,-,-,1
182,127 anos,-,-,-,-,-,-,-,-,-,...,-,-,-,-,-,-,-,-,-,1
183,Ignorado,1,-,2,1,-,1,2,2,3,...,1,-,4,3,-,2,1,-,21,142
184,Total,8648,3174,2357,7045,7608,1509,4826,4110,2212,...,8050,2301,8077,10740,8514,10538,8512,6383,2153,736774